"use client";

import React from "react";
import "@/style/accordion.css";

import {
  Accordion,
  AccordionItem,
  AccordionItemHeading,
  AccordionItemButton,
  AccordionItemPanel,
} from "react-accessible-accordion";

// Demo styles, see 'Styles' section below for some notes on use.
import "react-accessible-accordion/dist/fancy-example.css";

export default function Example() {
  return (
    <>
      <section className="flex justify-center py-20 px-5 bg-indigo-50">
        <div className="lg:max-w-[960px] md:max-w-[720px] sm:max-w-[540px] w-full">
          <h3 className="text-[40px] text-slate-800 font-bold text-center max-md:text-[24px] max-md:text-center text-wrap">
            Common queries, Clear answers
          </h3>
          {/* accordion start */}

          <ul className="w-[565px] max-w-full m-auto accordion-ul max-md:inline">
            <Accordion>
              <AccordionItem>
                <AccordionItemHeading>
                  <AccordionItemButton>
                    <li className="text-slate-800 text-lg font-normal leading-[30px] ">
                      Is my data used for training Paperpal’s AI? ?{" "}
                    </li>
                  </AccordionItemButton>
                </AccordionItemHeading>
                <AccordionItemPanel>
                  <p className="text-base text-slate-800 leading-[30px]">
                    No, your data is never used to train our AI models.
                    Additionally, you have full control over the data you
                    process using Paperpal. Your data used for Paperpal Copilot
                    and language checks, do not leave the Paperpal servers. For
                    more details, review our Terms of Use and Privacy Policy <span className="border-b cursor-pointer border-slate-800">data security policies.</span>
                  </p>
                </AccordionItemPanel>
              </AccordionItem>
              <AccordionItem>
                <AccordionItemHeading>
                  <AccordionItemButton>
                    <li className="text-slate-800 text-lg font-normal leading-[30px] ">
                      Does Paperpal use ChatGPT/GPT 3.5 or other GPT models?{" "}
                    </li>
                  </AccordionItemButton>
                </AccordionItemHeading>
                <AccordionItemPanel>
                  <p className="text-base text-slate-800 leading-[30px]">
                    Paperpal does not use any of the ChatGPT/ OpenAI models. We
                    use our own secure and proprietary suite of specialized AI
                    and generative AI models trained on scholarly data.
                  </p>
                </AccordionItemPanel>
              </AccordionItem>
              <AccordionItem>
                <AccordionItemHeading>
                  <AccordionItemButton>
                    <li className="text-slate-800 text-lg font-normal leading-[30px] ">
                      Will my Paperpal edited document be flagged as
                      plagiarised?
                    </li>
                  </AccordionItemButton>
                </AccordionItemHeading>
                <AccordionItemPanel>
                  <p className="text-base text-slate-800 leading-[30px]">
                    At a document level, unless the original manuscript has been
                    copied, it is very rare that it will be flagged by the
                    plagiarism checker tools. Also, at a sentence level, there
                    is a low possibility that text generated by Paperpal will
                    get flagged by a plagiarism checker. However, as the
                    rewrites suggested by Paperpal follow standard academic
                    sentence construction, there is a chance that a tools like
                    Turnitin might pick individual sentences as resembling
                    published literature.
                  </p>
                </AccordionItemPanel>
              </AccordionItem>
              <AccordionItem>
                <AccordionItemHeading>
                  <AccordionItemButton>
                    <li className="text-slate-800 text-lg font-normal leading-[30px] ">
                      Will my Paperpal edited document be flagged by AI
                      detectors?{" "}
                    </li>
                  </AccordionItemButton>
                </AccordionItemHeading>
                <AccordionItemPanel>
                  <p className="text-base text-slate-800 leading-[30px]">
                    Being flagged by AI detectors isn’t necessarily a bad thing.
                    Many authors use AI tools to improve writing and
                    productivity. AI detectors promote accountability to ensure
                    content is reliable. Understand the AI scoring, and then use
                    Paperpal’s output as a base to refine the text and express
                    ideas in your style. Secondly, note that AI detectors are in
                    the early stages of development. For example, one AI
                    detector falsely claimed the US Constitution was written by
                    AI. Therefore, these detectors can be used as a reference,
                    but should not be relied on for an accurate assessment.
                  </p>
                </AccordionItemPanel>
              </AccordionItem>
              <AccordionItem>
                <AccordionItemHeading>
                  <AccordionItemButton>
                    <li className="text-slate-800 text-lg font-normal leading-[30px] ">
                      Will I retain copyright over my Paperpal edited document?{" "}
                    </li>
                  </AccordionItemButton>
                </AccordionItemHeading>
                <AccordionItemPanel>
                  <p className="text-base text-slate-800 leading-[30px]">
                    Yes, you own copyright related to all content you produce
                    using Paperpal.
                  </p>
                </AccordionItemPanel>
              </AccordionItem>
            </Accordion>
          </ul>
        </div>
      </section>
    </>
  );
}
